source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JOEmojiableBtn_Example' do
  pod 'JOEmojiableBtn', :path => '../'
end

target 'JOEmojiableBtn_Tests' do
  pod 'JOEmojiableBtn', :path => '../'
end
